version: "3.9"

services:
  db:
    image: postgres:16
    container_name: aidmatch_db
    environment:
      POSTGRES_USER: aidmatch
      POSTGRES_PASSWORD: aidmatch
      POSTGRES_DB: aidmatch_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
